# Generated by Django 5.2.16 on 2026-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
