# Generated by Django 5.2.16 on 2026-07-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
